//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int DiscountID { get; set; }
        public decimal DiscountPercent { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModBy { get; set; }
        public System.DateTime ModDate { get; set; }
    }
}
