//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int DetailID { get; set; }
        public int OrderID { get; set; }
        public string ItemBarcode { get; set; }
        public int ItemCount { get; set; }
        public decimal Discount { get; set; }
        public decimal DetailPrice { get; set; }
        public bool IsValid { get; set; }
        public System.DateTime DatailDate { get; set; }
        public string Remarks { get; set; }
        public decimal UnitPrice { get; set; }
    }
}
